name: Release

on:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

env:
  HOSTNAME: ${{ secrets.LOCATION }}-docker.pkg.dev

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Authenticate Docker to Container Registry
      id: authenticate-docker 
      run: |
        echo '${{ secrets.SERVICE_ACCOUNT_KEY }}' | docker login -u _json_key --password-stdin https://$HOSTNAME
    - name: Build, Tag, and Push Image to Container Registry
      id: build-image
      run: |
        IMAGE_NAME=$(echo ${{ github.repository }} | cut -d/ -f2)
        IMAGE_TAG=$(echo ${{ github.ref }} | cut -d/ -f3)
        TAGGED_IMAGE=$HOSTNAME/${{ secrets.PROJECT_ID }}/${{ secrets.IMAGE_REPO }}/$IMAGE_NAME:$IMAGE_TAG
        docker build -t $TAGGED_IMAGE .
        docker push $TAGGED_IMAGE
    - name: Publish GitHub Release
      id: publish-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.sha }}
        draft: false 
        prerelease: false
